# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TripDiary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TripDiary
  pod 'RxSwift', '6.0.0'
  pod 'RxCocoa', '6.0.0'
  pod 'ReactorKit'
  pod 'Alamofire', '~> 5.2'
  
  target 'TripDiaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TripDiaryUITests' do
    # Pods for testing
  end

end
